# Generated by Django 6.0.7 on 2026-07-31 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('description', models.TextField(verbose_name='Опис')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ціна')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Кількість на складі')),
                ('weight', models.PositiveIntegerField(choices=[(250, '250g'), (500, '500g'), (1000, '1kg')], default=1000)),
                ('country_of_origin', models.CharField(default='Unknown', max_length=100, verbose_name='Країна виробник')),
                ('roast_level', models.CharField(choices=[('light', 'Light'), ('medium', 'Medium'), ('dark', 'Dark')], default='medium', max_length=20)),
                ('show_on_homepage', models.BooleanField(default=False, verbose_name='Показувати на головній сторінці')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Зображення')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
    ]
