# Generated by Django 6.0.7 on 2026-08-03 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='country_of_origin',
            new_name='country',
        ),
    ]
