# Generated by Django 6.0.7 on 2026-08-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_country_of_origin_product_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Unknown', max_length=100, verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='product',
            name='brief_description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Короткий опис'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Рекомендований продукт'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Новий продукт'),
        ),
    ]
